export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL';
export const CHANGE_LIMIT = 'CHANGE_LIMIT';

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const TOGGLE_UNIT = 'TOGGLE_UNIT';
